// Code generated by "stringer -type=Type"; DO NOT EDIT.

package object_change_type

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeLatest-2]
	_ = x[TypeHistorical-4]
}

const (
	_Type_name_0 = "TypeUnknown"
	_Type_name_1 = "TypeLatest"
	_Type_name_2 = "TypeHistorical"
)

func (i Type) String() string {
	switch {
	case i == 0:
		return _Type_name_0
	case i == 2:
		return _Type_name_1
	case i == 4:
		return _Type_name_2
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
