// Code generated by "stringer -type=PathOption"; DO NOT EDIT.

package store_fs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PathOptionDefault-0]
	_ = x[PathOptionLeft-1]
	_ = x[PathOptionMiddle-2]
	_ = x[PathOptionRight-3]
	_ = x[PathOptionTempLocal-4]
}

const _PathOption_name = "PathOptionDefaultPathOptionLeftPathOptionMiddlePathOptionRightPathOptionTempLocal"

var _PathOption_index = [...]uint8{0, 17, 31, 47, 62, 81}

func (i PathOption) String() string {
	if i < 0 || i >= PathOption(len(_PathOption_index)-1) {
		return "PathOption(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PathOption_name[_PathOption_index[i]:_PathOption_index[i+1]]
}
