#! /bin/bash -xe

dir="$(dirname "$0")/.."
lines="${1:-0}"
zit="$dir/build/zit"

cmd="xargs -0 caffeinate -imsd $zit new -filter $dir/bin/z_to_zit.awk"

if [[ "$lines" -eq 0 ]]; then
  find ~/Zettelkasten -type f -iname '*.md' -print0 \
    | $cmd
else
  find ~/Zettelkasten -type f -iname '*.md' -print0 \
    | ghead -z -n "$lines" \
    | $cmd
fi

