// Code generated by "stringer -type=SeqType"; DO NOT EDIT.

package box

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeqTypeUnknown-0]
	_ = x[SeqTypeIdentifier-1]
	_ = x[SeqTypeField-2]
}

const _SeqType_name = "SeqTypeUnknownSeqTypeIdentifierSeqTypeField"

var _SeqType_index = [...]uint8{0, 14, 31, 43}

func (i SeqType) String() string {
	if i < 0 || i >= SeqType(len(_SeqType_index)-1) {
		return "SeqType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SeqType_name[_SeqType_index[i]:_SeqType_index[i+1]]
}
