// Code generated by "stringer -type=Schlussel"; DO NOT EDIT.

package schlussel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
}

const _Schlussel_name = "Unknown"

var _Schlussel_index = [...]uint8{0, 7}

func (i Schlussel) String() string {
	if i >= Schlussel(len(_Schlussel_index)-1) {
		return "Schlussel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Schlussel_name[_Schlussel_index[i]:_Schlussel_index[i+1]]
}
