// Code generated by "stringer -type=Priority"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[P0-0]
	_ = x[P1-1]
	_ = x[P2-2]
	_ = x[P3-3]
	_ = x[P4-4]
	_ = x[P5-5]
}

const _Priority_name = "P0P1P2P3P4P5"

var _Priority_index = [...]uint8{0, 2, 4, 6, 8, 10, 12}

func (i Priority) String() string {
	if i < 0 || i >= Priority(len(_Priority_index)-1) {
		return "Priority(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Priority_name[_Priority_index[i]:_Priority_index[i+1]]
}
