// Code generated by "stringer -type=diffType"; DO NOT EDIT.

package chrome

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[diffTypeIgnore-0]
	_ = x[diffTypeNew-1]
	_ = x[diffTypeChange-2]
	_ = x[diffTypeDelete-3]
}

const _diffType_name = "diffTypeIgnorediffTypeNewdiffTypeChangediffTypeDelete"

var _diffType_index = [...]uint8{0, 14, 25, 39, 53}

func (i diffType) String() string {
	if i < 0 || i >= diffType(len(_diffType_index)-1) {
		return "diffType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _diffType_name[_diffType_index[i]:_diffType_index[i+1]]
}
