// Code generated by "stringer -type=Type"; DO NOT EDIT.

package etiketten_path

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeDirect-0]
	_ = x[TypeSuper-1]
	_ = x[TypeIndirect-2]
}

const _Type_name = "TypeDirectTypeSuperTypeIndirect"

var _Type_index = [...]uint8{0, 10, 19, 31}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
