// Code generated by "stringer -type=FileType"; DO NOT EDIT.

package files

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileTypeUnknown-0]
	_ = x[FileTypeText-1]
	_ = x[FileTypeExecutable-2]
	_ = x[FileTypeData-3]
}

const _FileType_name = "FileTypeUnknownFileTypeTextFileTypeExecutableFileTypeData"

var _FileType_index = [...]uint8{0, 15, 27, 45, 57}

func (i FileType) String() string {
	if i >= FileType(len(_FileType_index)-1) {
		return "FileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileType_name[_FileType_index[i]:_FileType_index[i+1]]
}
