// Code generated by "stringer -type=RemoteServeType"; DO NOT EDIT.

package repo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RemoteServeTypeUnspecified-0]
	_ = x[RemoteServeTypeSocketUnix-1]
	_ = x[RemoteServeTypePortHTTP-2]
	_ = x[RemoteServeTypeStdioLocal-3]
}

const _RemoteServeType_name = "RemoteServeTypeUnspecifiedRemoteServeTypeSocketUnixRemoteServeTypePortHTTPRemoteServeTypeStdioLocal"

var _RemoteServeType_index = [...]uint8{0, 26, 51, 74, 99}

func (i RemoteServeType) String() string {
	if i < 0 || i >= RemoteServeType(len(_RemoteServeType_index)-1) {
		return "RemoteServeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RemoteServeType_name[_RemoteServeType_index[i]:_RemoteServeType_index[i+1]]
}
