// Code generated by "stringer -type=entryType"; DO NOT EDIT.

package log_remote_inventory_lists

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EntryTypeSent-0]
	_ = x[EntryTypeReceived-1]
}

const _entryType_name = "EntryTypeSentEntryTypeReceived"

var _entryType_index = [...]uint8{0, 13, 30}

func (i entryType) String() string {
	if i >= entryType(len(_entryType_index)-1) {
		return "entryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _entryType_name[_entryType_index[i]:_entryType_index[i+1]]
}
