[package]
name = "akte-store"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.14", features = ["derive"] }
hex = "0.4.3"
hex-literal = "0.4.1"
io_tee = "0.1.1"
rand = "0.8.5"
rust-crypto = "0.2.36"
