// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package object_mode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeEmpty-0]
	_ = x[ModeAddToInventoryList-2]
	_ = x[ModeUpdateTai-4]
	_ = x[ModeLatest-8]
	_ = x[ModeMergeCheckedOut-16]
	_ = x[ModeApplyProto-32]
	_ = x[ModeHooks-64]
}

const (
	_Mode_name_0 = "ModeEmpty"
	_Mode_name_1 = "ModeAddToInventoryList"
	_Mode_name_2 = "ModeUpdateTai"
	_Mode_name_3 = "ModeLatest"
	_Mode_name_4 = "ModeMergeCheckedOut"
	_Mode_name_5 = "ModeApplyProto"
	_Mode_name_6 = "ModeHooks"
)

func (i Mode) String() string {
	switch {
	case i == 0:
		return _Mode_name_0
	case i == 2:
		return _Mode_name_1
	case i == 4:
		return _Mode_name_2
	case i == 8:
		return _Mode_name_3
	case i == 16:
		return _Mode_name_4
	case i == 32:
		return _Mode_name_5
	case i == 64:
		return _Mode_name_6
	default:
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
