// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token_types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeIncomplete-0]
	_ = x[TypeOperator-1]
	_ = x[TypeIdentifier-2]
	_ = x[TypeLiteral-3]
	_ = x[TypeField-4]
}

const _TokenType_name = "TypeIncompleteTypeOperatorTypeIdentifierTypeLiteralTypeField"

var _TokenType_index = [...]uint8{0, 14, 26, 40, 51, 60}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
