#! /bin/bash -xe

prefix=code.linenisgreat.com/zit/go/zit
original="${1%/}"
renamed="${2%/}"

original_pkg="$(basename "$original")"
renamed_pkg="$(basename "$renamed")"

gofmt -w -r "$original_pkg.E -> $renamed_pkg.E" ./
gofmt -w -r "$original_pkg -> $renamed_pkg" ./

mkdir -p "$renamed"

git mv $original/* "$renamed" || mv $original/* "$renamed"
find src -type d -empty -delete

# https://unix.stackexchange.com/questions/190334/sed-word-boundaries-on-macos
declare -r sed_script="
  s|\\b$prefix/$original\\b|$prefix/$renamed|g;
  s|^package $original_pkg\$|package $renamed_pkg|g;
"

ag "$prefix/$original" -l0 |
  xargs -0 sed -i'' "$sed_script"

./bin/fix_redundant_import_alisas.bash
goimports -w ./

go build -o /dev/null
