// Code generated by "stringer -type=DialogueType"; DO NOT EDIT.

package remote_conn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DialogueTypeMain-0]
	_ = x[DialogueTypeSkusForFilter-1]
	_ = x[DialogueTypeObjekten-2]
	_ = x[DialogueTypeAkten-3]
	_ = x[DialogueTypeObjekteReader-4]
	_ = x[DialogueTypeAkteReader-5]
	_ = x[DialogueTypeObjekteWriter-6]
	_ = x[DialogueTypeAkteWriter-7]
	_ = x[DialogueTypePull-8]
	_ = x[DialogueTypePullAkte-9]
	_ = x[DialogueTypePush-10]
	_ = x[DialogueTypePushObjekten-11]
	_ = x[DialogueTypePushAkte-12]
	_ = x[DialogueTypeGetNeededSkus-13]
}

const _DialogueType_name = "DialogueTypeMainDialogueTypeSkusForFilterDialogueTypeObjektenDialogueTypeAktenDialogueTypeObjekteReaderDialogueTypeAkteReaderDialogueTypeObjekteWriterDialogueTypeAkteWriterDialogueTypePullDialogueTypePullAkteDialogueTypePushDialogueTypePushObjektenDialogueTypePushAkteDialogueTypeGetNeededSkus"

var _DialogueType_index = [...]uint16{0, 16, 41, 61, 78, 103, 125, 150, 172, 188, 208, 224, 248, 268, 293}

func (i DialogueType) String() string {
	if i < 0 || i >= DialogueType(len(_DialogueType_index)-1) {
		return "DialogueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DialogueType_name[_DialogueType_index[i]:_DialogueType_index[i+1]]
}
