// Code generated by "stringer -type=DialogueType"; DO NOT EDIT.

package remote_conn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DialogueTypeMain-0]
	_ = x[DialogueTypeSkusForFilter-1]
	_ = x[DialogueTypeObjekten-2]
	_ = x[DialogueTypeAkten-3]
	_ = x[DialogueTypeObjekteReaderForSku-4]
	_ = x[DialogueTypeAkteReaderForSha-5]
	_ = x[DialogueTypePull-6]
	_ = x[DialogueTypePullAkte-7]
	_ = x[DialogueTypePush-8]
	_ = x[DialogueTypePushObjekten-9]
	_ = x[DialogueTypePushAkte-10]
}

const _DialogueType_name = "DialogueTypeMainDialogueTypeSkusForFilterDialogueTypeObjektenDialogueTypeAktenDialogueTypeObjekteReaderForSkuDialogueTypeAkteReaderForShaDialogueTypePullDialogueTypePullAkteDialogueTypePushDialogueTypePushObjektenDialogueTypePushAkte"

var _DialogueType_index = [...]uint8{0, 16, 41, 61, 78, 109, 137, 153, 173, 189, 213, 233}

func (i DialogueType) String() string {
	if i < 0 || i >= DialogueType(len(_DialogueType_index)-1) {
		return "DialogueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DialogueType_name[_DialogueType_index[i]:_DialogueType_index[i+1]]
}
