schema = 3

[mod]
  [mod."code.linenisgreat.com/chrest/go"]
    version = "v0.0.0-20241228133601-d8eb38b220ac"
    hash = "sha256-ztnmEvEs9kLi0LLGycK/bWYYG1ikGcHIf/mzCaQDmoo="
  [mod."filippo.io/age"]
    version = "v1.2.1"
    hash = "sha256-9ZJdrmqBj43zSvStt0r25wjSfnvitdx3GYtM3urHcaA="
  [mod."github.com/DataDog/zstd"]
    version = "v1.5.6"
    hash = "sha256-YbP+KGCzKkIFAqqg1nVADL7poUzWX1KwytKgy8rn6xI="
  [mod."github.com/brandondube/tai"]
    version = "v0.1.0"
    hash = "sha256-o32wvMW6waT/vJJkpjiCGxBNBUsqeAvnARhbsikRk50="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/shlex"]
    version = "v0.0.0-20191202100458-e7afc7fbc510"
    hash = "sha256-1f392pCmS7AXVKXIC1SvKlYtK/rvW47F5CCkGT2G6JM="
  [mod."github.com/gorilla/mux"]
    version = "v1.8.1"
    hash = "sha256-nDABvAhlYgxUW2N/brrep7NkQXoSGcHhA+XI4+tK0F0="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.3"
    hash = "sha256-fE++SVgnCGdnFZoROHWuYjIR7ENl7k9KKxQrRTquv/o="
  [mod."github.com/yuin/gopher-lua"]
    version = "v1.1.1"
    hash = "sha256-f7clAQeOHKQ3pL9ibNgXvc9QnIEvlMzm5SlWEDkj5tk="
  [mod."golang.org/x/crypto"]
    version = "v0.31.0"
    hash = "sha256-ZBjoG7ZOuTEmjaXPP9txAvjAjC46DeaLs0zrNzi8EQw="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20241217172543-b2144cdd0a67"
    hash = "sha256-b+OVYsAPa3wAJKwvxKPz3goepavGvQomsk1Rs8pnSQU="
  [mod."golang.org/x/sys"]
    version = "v0.28.0"
    hash = "sha256-kzSlDo5FKsQU9cLefIt2dueGUfz9XuEW+mGSGlPATGc="
  [mod."golang.org/x/term"]
    version = "v0.27.0"
    hash = "sha256-cb5p/yOlVL7dbkxugUVfqESTVpZ2LtrUWPnx9yue3r0="
  [mod."golang.org/x/text"]
    version = "v0.21.0"
    hash = "sha256-QaMwddBRnoS2mv9Y86eVC2x2wx/GZ7kr2zAJvwDeCPc="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20240903120638-7835f813f4da"
    hash = "sha256-bE7CcrnAvryNvM26ieJGXqbAtuLwHaGcmtVMsVnksqo="
