schema = 3

[mod]
  [mod."code.linenisgreat.com/chrest/go/chrest"]
    version = "v0.0.0-20240623175136-220b0978299b"
    hash = "sha256-/EWBMLRiGojods6yv2xe6ME70cqFkv82j7hikHwJINc="
  [mod."filippo.io/age"]
    version = "v1.1.1"
    hash = "sha256-LRxxJQLQkzoCNYGS/XBixVmYXoZ1mPHKvFicPGXYLcw="
  [mod."github.com/DataDog/zstd"]
    version = "v1.5.5"
    hash = "sha256-tSw0aq0pPyroZtQYYb9lWOtPVNaQOt8skYQ4TMXGvAQ="
  [mod."github.com/brandondube/tai"]
    version = "v0.1.0"
    hash = "sha256-o32wvMW6waT/vJJkpjiCGxBNBUsqeAvnARhbsikRk50="
  [mod."github.com/google/shlex"]
    version = "v0.0.0-20191202100458-e7afc7fbc510"
    hash = "sha256-1f392pCmS7AXVKXIC1SvKlYtK/rvW47F5CCkGT2G6JM="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.1.1"
    hash = "sha256-BQtflYQ8Dt7FL/yFI9OnxwvsRk0oEO37ZXuGXFveVpo="
  [mod."github.com/yuin/gopher-lua"]
    version = "v1.1.1"
    hash = "sha256-f7clAQeOHKQ3pL9ibNgXvc9QnIEvlMzm5SlWEDkj5tk="
  [mod."golang.org/x/crypto"]
    version = "v0.21.0"
    hash = "sha256-Z4k1LvFh4Jai7HUe6TTuXSG3VnuiRpMwdARIdZZqSYk="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240506185415-9bf2ced13842"
    hash = "sha256-5JZE4OhePWHtObIT4RJOS+2zv265Io1yJkFeE8wHXY4="
  [mod."golang.org/x/sys"]
    version = "v0.18.0"
    hash = "sha256-bIFhfFp7Sj0E1gcE3X3l/jecCfSRLgrkb8f0Yr6tVR0="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20231012003039-104605ab7028"
    hash = "sha256-IsFTm5WZQ6W1ZDF8WOP+6xiOAc7pIq8r9Afvkjp3PRQ="
