
cmd_bats := "BATS_TEST_TIMEOUT=$(timeout) bats --tap --jobs $(n_prc)"

gen-fixture:
 ./zz-tests_bats/migration/generate_fixture.bash

end-to-end-tests:
  {{cmd_bats}} zz-tests_bats/*.bats

test:
  #! /usr/bin/env -S bash -xe
  pushd "{{invocation_directory()}}"
  make build/zit
  pushd "$HOME/zit"
  echo "TODO: insert test function"
  exit 1

precommit:
  make build/zit
  ./zz-tests_bats/migration/generate_fixture.bash
  make build/tests_slower
