// Code generated by "stringer -type=DialogueType"; DO NOT EDIT.

package remote_conn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DialogueTypeMain-0]
	_ = x[DialogueTypeSkusForFilter-1]
	_ = x[DialogueTypeObjects-2]
	_ = x[DialogueTypeBlobs-3]
	_ = x[DialogueTypeObjectReader-4]
	_ = x[DialogueTypeBlobReader-5]
	_ = x[DialogueTypeObjectWriter-6]
	_ = x[DialogueTypeBlobWriter-7]
	_ = x[DialogueTypePull-8]
	_ = x[DialogueTypePullBLob-9]
	_ = x[DialogueTypePush-10]
	_ = x[DialogueTypePushObjects-11]
	_ = x[DialogueTypePushBlob-12]
	_ = x[DialogueTypeGetNeededSkus-13]
}

const _DialogueType_name = "DialogueTypeMainDialogueTypeSkusForFilterDialogueTypeObjectsDialogueTypeBlobsDialogueTypeObjectReaderDialogueTypeBlobReaderDialogueTypeObjectWriterDialogueTypeBlobWriterDialogueTypePullDialogueTypePullBLobDialogueTypePushDialogueTypePushObjectsDialogueTypePushBlobDialogueTypeGetNeededSkus"

var _DialogueType_index = [...]uint16{0, 16, 41, 60, 77, 101, 123, 147, 169, 185, 205, 221, 244, 264, 289}

func (i DialogueType) String() string {
	if i < 0 || i >= DialogueType(len(_DialogueType_index)-1) {
		return "DialogueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DialogueType_name[_DialogueType_index[i]:_DialogueType_index[i+1]]
}
