name: Publish every Git push to main to FlakeHub
 
on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./go/zit

jobs:

  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@main"
        with:
          determinate: true
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "friedenberg/zit-go"
          rolling: true
          visibility: "public"
          include-output-paths: true
          directory: ./go/zit

  build-nix-package:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix build
        working-directory: ./go/zit
